# Generated by Django 4.2.7 on 2023-11-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_model',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
